In [2]:
import pandas as pd
df=pd.read_csv('FMCG_2022_2024.csv')

In [3]:
import pandas as pd
df=pd.read_csv('FMCG_2022_2024.csv')
df.head()

,date,sku,brand,segment,category,channel,region,pack_type,price_unit,promotion_flag,delivery_days,stock_available,delivered_qty,units_sold
0,1/21/2022,MI-006,MiBrand1,Milk-Seg3,Milk,Retail,PL-Central,Multipack,2.38,0,1,141,128,9
1,1/21/2022,MI-006,MiBrand1,Milk-Seg3,Milk,Retail,PL-North,Single,1.55,1,3,0,129,0
2,1/21/2022,MI-006,MiBrand1,Milk-Seg3,Milk,Retail,PL-South,Carton,4.00,0,5,118,161,8
3,1/21/2022,MI-006,MiBrand1,Milk-Seg3,Milk,Discount,PL-Central,Single,5.16,0,2,81,114,7
4,1/21/2022,MI-006,MiBrand1,Milk-Seg3,Milk,Discount,PL-North,Single,7.66,0,4,148,204,12

In [4]:
import pandas as pd
df=pd.read_csv('FMCG_2022_2024.csv')
df.head()

,date,sku,brand,segment,category,channel,region,pack_type,price_unit,promotion_flag,delivery_days,stock_available,delivered_qty,units_sold
0,1/21/2022,MI-006,MiBrand1,Milk-Seg3,Milk,Retail,PL-Central,Multipack,2.38,0,1,141,128,9
1,1/21/2022,MI-006,MiBrand1,Milk-Seg3,Milk,Retail,PL-North,Single,1.55,1,3,0,129,0
2,1/21/2022,MI-006,MiBrand1,Milk-Seg3,Milk,Retail,PL-South,Carton,4.00,0,5,118,161,8
3,1/21/2022,MI-006,MiBrand1,Milk-Seg3,Milk,Discount,PL-Central,Single,5.16,0,2,81,114,7
4,1/21/2022,MI-006,MiBrand1,Milk-Seg3,Milk,Discount,PL-North,Single,7.66,0,4,148,204,12

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 190757 entries, 0 to 190756
Data columns (total 14 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   date             190757 non-null  str
 1   sku              190757 non-null  str
 2   brand            190757 non-null  str
 3   segment          190757 non-null  str
 4   category         190757 non-null  str
 5   channel          190757 non-null  str
 6   region           190757 non-null  str
 7   pack_type        190757 non-null  str
 8   price_unit       190757 non-null  float64
 9   promotion_flag   190757 non-null  int64
 10  delivery_days    190757 non-null  int64
 11  stock_available  190757 non-null  int64
 12  delivered_qty    190757 non-null  int64
 13  units_sold       190757 non-null  int64
dtypes: float64(1), int64(5), str(8)
memory usage: 20.4 MB

In [6]:
df.describe()

,price_unit,promotion_flag,delivery_days,stock_available,delivered_qty,units_sold
count,190757.000000,190757.000000,190757.000000,190757.000000,190757.000000,190757.000000
mean,5.251979,0.149200,3.004860,157.697652,179.333655,19.919709
std,2.166705,0.356287,1.414626,52.736104,40.037475,11.770077
min,1.500000,0.000000,1.000000,-12.000000,-11.000000,-25.000000
25%,3.380000,0.000000,2.000000,124.000000,152.000000,12.000000
50%,5.250000,0.000000,3.000000,155.000000,179.000000,18.000000
75%,7.130000,0.000000,4.000000,192.000000,206.000000,25.000000
max,9.000000,1.000000,5.000000,405.000000,366.000000,139.000000

In [7]:
print("Negative stock_available:",(df['stock_available']<0).sum())
print("Negative delivery_qty:",(df['delivered_qty']<0).sum())

Negative stock_available: 3
Negative delivery_qty: 3

In [8]:
print("Negative units_sold:", (df['units_sold'] < 0).sum())

Negative units_sold: 3

In [9]:
df = df[(df['stock_available'] >= 0) & (df['delivered_qty'] >= 0) & (df['units_sold'] >= 0)]
print(df.shape)

(190754, 14)

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df['date']=pd.to_datetime(df['date'])

In [12]:
df['month']=df['date'].dt.month

In [13]:
df['quarter']=df['date'].dt.quarter

In [14]:
df['day_of_week']=df['date'].dt.dayofweek

In [15]:
df.head()

,date,sku,brand,segment,category,channel,region,pack_type,price_unit,promotion_flag,delivery_days,stock_available,delivered_qty,units_sold,month,quarter,day_of_week
0,2022-01-21,MI-006,MiBrand1,Milk-Seg3,Milk,Retail,PL-Central,Multipack,2.38,0,1,141,128,9,1,1,4
1,2022-01-21,MI-006,MiBrand1,Milk-Seg3,Milk,Retail,PL-North,Single,1.55,1,3,0,129,0,1,1,4
2,2022-01-21,MI-006,MiBrand1,Milk-Seg3,Milk,Retail,PL-South,Carton,4.00,0,5,118,161,8,1,1,4
3,2022-01-21,MI-006,MiBrand1,Milk-Seg3,Milk,Discount,PL-Central,Single,5.16,0,2,81,114,7,1,1,4
4,2022-01-21,MI-006,MiBrand1,Milk-Seg3,Milk,Discount,PL-North,Single,7.66,0,4,148,204,12,1,1,4

In [16]:
df.info()

<class 'pandas.DataFrame'>
Index: 190754 entries, 0 to 190756
Data columns (total 17 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   date             190754 non-null  datetime64[us]
 1   sku              190754 non-null  str
 2   brand            190754 non-null  str
 3   segment          190754 non-null  str
 4   category         190754 non-null  str
 5   channel          190754 non-null  str
 6   region           190754 non-null  str
 7   pack_type        190754 non-null  str
 8   price_unit       190754 non-null  float64
 9   promotion_flag   190754 non-null  int64
 10  delivery_days    190754 non-null  int64
 11  stock_available  190754 non-null  int64
 12  delivered_qty    190754 non-null  int64
 13  units_sold       190754 non-null  int64
 14  month            190754 non-null  int32
 15  quarter          190754 non-null  int32
 16  day_of_week      190754 non-null  int32
dtypes: datetime64[us](1), float64(1), int32(3), int64(5), str(7)
memory usage: 24.0 MB

In [17]:
df.info()

<class 'pandas.DataFrame'>
Index: 190754 entries, 0 to 190756
Data columns (total 17 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   date             190754 non-null  datetime64[us]
 1   sku              190754 non-null  str
 2   brand            190754 non-null  str
 3   segment          190754 non-null  str
 4   category         190754 non-null  str
 5   channel          190754 non-null  str
 6   region           190754 non-null  str
 7   pack_type        190754 non-null  str
 8   price_unit       190754 non-null  float64
 9   promotion_flag   190754 non-null  int64
 10  delivery_days    190754 non-null  int64
 11  stock_available  190754 non-null  int64
 12  delivered_qty    190754 non-null  int64
 13  units_sold       190754 non-null  int64
 14  month            190754 non-null  int32
 15  quarter          190754 non-null  int32
 16  day_of_week      190754 non-null  int32
dtypes: datetime64[us](1), float64(1), int32(3), int64(5), str(7)
memory usage: 24.0 MB

In [18]:
df.info()

<class 'pandas.DataFrame'>
Index: 190754 entries, 0 to 190756
Data columns (total 17 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   date             190754 non-null  datetime64[us]
 1   sku              190754 non-null  str
 2   brand            190754 non-null  str
 3   segment          190754 non-null  str
 4   category         190754 non-null  str
 5   channel          190754 non-null  str
 6   region           190754 non-null  str
 7   pack_type        190754 non-null  str
 8   price_unit       190754 non-null  float64
 9   promotion_flag   190754 non-null  int64
 10  delivery_days    190754 non-null  int64
 11  stock_available  190754 non-null  int64
 12  delivered_qty    190754 non-null  int64
 13  units_sold       190754 non-null  int64
 14  month            190754 non-null  int32
 15  quarter          190754 non-null  int32
 16  day_of_week      190754 non-null  int32
dtypes: datetime64[us](1), float64(1), int32(3), int64(5), str(7)
memory usage: 24.0 MB

In [19]:
df.groupby('category')['units_sold'].sum().sort_values(ascending=False)

category
Yogurt       1566582
Milk          782734
ReadyMeal     678842
SnackBar      647353
Juice         124349
Name: units_sold, dtype: int64

In [20]:
df.groupby('region')['units_sold'].mean().sort_values(ascending=False)

region
PL-North      19.959494
PL-South      19.941399
PL-Central    19.859670
Name: units_sold, dtype: float64

In [21]:
df.groupby('promotion_flag')['units_sold'].mean()

promotion_flag
0    17.440183
1    34.062649
Name: units_sold, dtype: float64

In [22]:
df.groupby('month')['units_sold'].sum()

month
1     221776
2     235912
3     290669
4     318262
5     360484
6     371991
7     395452
8     361307
9     317047
10    313797
11    298884
12    314279
Name: units_sold, dtype: int64

In [23]:
df.describe()

,date,price_unit,promotion_flag,delivery_days,stock_available,delivered_qty,units_sold,month,quarter,day_of_week
count,190754,190754.000000,190754.000000,190754.000000,190754.000000,190754.000000,190754.000000,190754.000000,190754.000000,190754.000000
mean,2023-10-28 04:11:30.581586,5.251989,0.149197,3.004839,157.700237,179.336585,19.920211,6.953233,2.644778,2.996834
min,2022-01-21 00:00:00,1.500000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000
25%,2023-04-16 00:00:00,3.380000,0.000000,2.000000,124.000000,152.000000,12.000000,4.000000,2.000000,1.000000
50%,2023-11-12 00:00:00,5.250000,0.000000,3.000000,155.000000,179.000000,18.000000,7.000000,3.000000,3.000000
75%,2024-06-07 00:00:00,7.130000,0.000000,4.000000,192.000000,206.000000,25.000000,10.000000,4.000000,5.000000
max,2024-12-31 00:00:00,9.000000,1.000000,5.000000,405.000000,366.000000,139.000000,12.000000,4.000000,6.000000
std,NaN,2.166692,0.356284,1.414626,52.732487,40.030968,11.769429,3.374969,1.094647,2.002745

In [24]:
df.info()

<class 'pandas.DataFrame'>
Index: 190754 entries, 0 to 190756
Data columns (total 17 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   date             190754 non-null  datetime64[us]
 1   sku              190754 non-null  str
 2   brand            190754 non-null  str
 3   segment          190754 non-null  str
 4   category         190754 non-null  str
 5   channel          190754 non-null  str
 6   region           190754 non-null  str
 7   pack_type        190754 non-null  str
 8   price_unit       190754 non-null  float64
 9   promotion_flag   190754 non-null  int64
 10  delivery_days    190754 non-null  int64
 11  stock_available  190754 non-null  int64
 12  delivered_qty    190754 non-null  int64
 13  units_sold       190754 non-null  int64
 14  month            190754 non-null  int32
 15  quarter          190754 non-null  int32
 16  day_of_week      190754 non-null  int32
dtypes: datetime64[us](1), float64(1), int32(3), int64(5), str(7)
memory usage: 24.0 MB

In [25]:
features=df[['category','channel','region','pack_type','price_unit','promotion__flag','delivery_days','month','quarter','day_of_week']]

KeyError: "['promotion__flag'] not in index"

In [26]:
features=df[['category','channel','region','pack_type','price_unit','promotion_flag','delivery_days','month','quarter','day_of_week']]

In [27]:
features_encoded=pd.get_dumies(features,columns=['category','channel', 'region', 'pack_type'],drop_first=true)

AttributeError: module 'pandas' has no attribute 'get_dumies'

In [28]:
features_encoded=pd.get_dummies(features,columns=['category','channel', 'region', 'pack_type'],drop_first=true)

NameError: name 'true' is not defined

In [29]:
features_encoded=pd.get_dummies(features,columns=['category','channel', 'region', 'pack_type'],drop_first=True)

In [30]:
features_encoded.head()

,price_unit,promotion_flag,delivery_days,month,quarter,day_of_week,category_Milk,category_ReadyMeal,category_SnackBar,category_Yogurt,channel_E-commerce,channel_Retail,region_PL-North,region_PL-South,pack_type_Multipack,pack_type_Single
0,2.38,0,1,1,1,4,True,False,False,False,False,True,False,False,True,False
1,1.55,1,3,1,1,4,True,False,False,False,False,True,True,False,False,True
2,4.00,0,5,1,1,4,True,False,False,False,False,True,False,True,False,False
3,5.16,0,2,1,1,4,True,False,False,False,False,False,False,False,False,True
4,7.66,0,4,1,1,4,True,False,False,False,False,False,True,False,False,True

In [31]:
df['category'].unique()

<StringArray>
['Milk', 'Yogurt', 'ReadyMeal', 'Juice', 'SnackBar']
Length: 5, dtype: str

In [32]:
X=features_encoded

In [33]:
y=df['units_sold']

In [34]:
print(X.shape())

TypeError: 'tuple' object is not callable

In [35]:
print(X.shape)

(190754, 16)

In [36]:
print(y.shape)

(190754,)

In [37]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=test_train_split(X,y,test_size=0.2,random_state=42)

NameError: name 'test_train_split' is not defined

In [38]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [39]:
print(X.train.shape,X_test.shape)

AttributeError: 'DataFrame' object has no attribute 'train'

In [40]:
print(X_train.shape,X_test.shape)

(152603, 16) (38151, 16)

In [42]:
from sklearn.linear_model import LinearRegression

In [43]:
lr_model=LinearRegression()

In [44]:
lr_model.fit(X_train,y_train)

LinearRegression()

In [45]:
y_pred_lr=lr_model.predict(X_test)

In [46]:
y_pred_lr.head

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [47]:
y_pred_lr.head()

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [48]:
y_pred_lr[:5]

array([20.69135422, 18.41385868, 19.87319806, 13.2614751 , 16.043114  ])

In [49]:
from sklearn.metrics import mean_squared_error,r2_score
import numpy as np
rmse_lr=np.sqrt(mean_squared_error(y_test,y_pred_lr))
r2_lr=r2_score(y_test,y_pred_lr)
print('Linear Regression RMSE:', rmse_lr)
print('Linear Regression R2:', r2_lr)

Linear Regression RMSE: 9.891010670586086
Linear Regression R2: 0.2828456214238251

In [50]:
from sklearn.tree import DecisionTreeRegressor
dt_model = DecisionTreeRegressor(max_depth=6, random_state=42)
dt_model.fit(X_train, y_train)
y_pred_dt = dt_model.predict(X_test)

rmse_dt = np.sqrt(mean_squared_error(y_test, y_pred_dt))
r2_dt = r2_score(y_test, y_pred_dt)

print('Decision Tree RMSE:', rmse_dt)
print('Decision Tree R2:', r2_dt)

Decision Tree RMSE: 9.330119317204664
Decision Tree R2: 0.3618750741255333

In [51]:
coefficients = pd.DataFrame({'feature': X.columns, 'coefficient': lr_model.coef_})
coefficients.sort_values('coefficient', ascending=False).head(10)

               feature  coefficient
1       promotion_flag    16.589920
9      category_Yogurt     3.602401
8    category_SnackBar     2.274367
7   category_ReadyMeal     1.933628
10  channel_E-commerce     0.114396
12     region_PL-North     0.049671
11      channel_Retail     0.035678
15    pack_type_Single     0.031581
13     region_PL-South     0.028149
2        delivery_days     0.026520